---
- hosts: devstack
  vars_files: 
    - zuul-params.yaml

  tasks:
    - name: Include variables from group_vars/devstack-{{ zuul_project | basename }}
      include_vars: "group_vars/devstack-{{ zuul_project | basename }}"
      tags: always
 
    - include: tasks/devstack/configure-sudoers.yaml

    - include: tasks/devstack/run-unstack.yaml

    - include: tasks/devstack/install-apt-packages.yaml
    - include: tasks/devstack/install-pip.yaml
    - include: tasks/devstack/configure-pip-index.yaml
    - include: tasks/devstack/install-python-packages.yaml

    - include: tasks/devstack/find-data-port.yaml
    - include: tasks/devstack/configure-ovs.yaml

    - include: tasks/devstack/install-zuul.yaml
    - include: tasks/devstack/prepare-git-repos.yaml
    - include: tasks/devstack/install-networking-hyperv.yaml

    - include: tasks/devstack/write-configs.yaml

    - include: tasks/devstack/run-stack.yaml
