---
- hosts: devstack
  vars_files: 
    - zuul-params.yaml

  tasks:
    - name: Include variables from group_vars/devstack-{{ zuul_project | basename }}
      include_vars: "group_vars/devstack-{{ zuul_project | basename }}"
 
    - include: configure-sudoers.yaml

    - include: run-unstack.yaml

    - include: install-apt-packages.yaml
    - include: install-pip.yaml
    - include: configure-pip-index.yaml
    - include: install-python-packages.yaml

    - include: find-data-port.yaml
    - include: configure-ovs.yaml

    - include: install-zuul.yaml
    - include: prepare-git-repos.yaml
    - include: install-networking-hyperv.yaml

    - include: write-configs.yaml

    - include: run-stack.yaml
