---
- hosts: win2016-compute
  any_errors_fatal: true
  vars_files: 
    - zuul-params.yaml
    - group_vars/windows

  tasks:
    - name: Include variables from group_vars/win2016-compute-{{ zuul_project | basename }}
      include_vars: "group_vars/win2016-compute-{{ zuul_project | basename }}"
      failed_when: False
      tags: always

    - name: Include variables from group_vars/win2016-compute-{{ zuul_project | basename }}-{{ job_type }}
      include_vars: "group_vars/win2016-compute-{{ zuul_project | basename }}-{{ job_type }}"
      failed_when: False
      tags: always

    # Run sanity checks as early as possible
    - include: tasks/windows/sanity-checks.yaml
    - name: Install FS-iSCSITarget-Server
      win_feature:
        name: FS-iSCSITarget-Server
        state: present
      when: job_type == "iscsi"

    - include: build-win2016.yaml
