- hosts: win2016-compute,win2016-cinder

  vars_files: 
    - zuul-params.yaml

  tasks:
    - name: Include variables from group_vars/windows
      include_vars: "group_vars/windows"
      failed_when: False
      tags: always

    - name: Include variables from group_vars/devstack
      include_vars: "group_vars/devstack"
      failed_when: False
      tags: always

    - name: Include variables from group_vars/devstack-{{ zuul_project | basename }}
      include_vars: "group_vars/devstack-{{ zuul_project | basename }}"
      failed_when: False
      tags: always 

    - name: Include variables from group_vars/devstack-{{ zuul_project | basename }}-{{ job_type }}
      include_vars: "group_vars/devstack-{{ zuul_project | basename }}-{{ job_type }}"
      failed_when: False
      when: job_type is defined
      tags: always

    - name: Include variables from group_vars/devstack-{{ zuul_project | basename }}-{{ network_type }}
      include_vars: "group_vars/devstack-{{ zuul_project | basename }}-{{ network_type }}"
      failed_when: False
      when: network_type is defined and job_type is not defined
      tags: always

    - name: Include variables from group_vars/devstack-{{ zuul_project | basename }}-{{ job_type }}-{{ network_type }}
      include_vars: "group_vars/devstack-{{ zuul_project | basename }}-{{ job_type }}-{{ network_type }}"
      failed_when: False
      when: job_type is defined and network_type is defined
      tags: always

    - name: Include variables from group_vars/win2016-compute
      include_vars: "group_vars/win2016-compute"
      failed_when: False
      tags: always

    - name: Include variables from group_vars/win2016-compute-{{ zuul_project | basename }}
      include_vars: "group_vars/win2016-compute-{{ zuul_project | basename }}"
      failed_when: False
      tags: always

    - name: Include variables from group_vars/win2016-compute-{{ zuul_project | basename }}-{{ job_type }}
      include_vars: "group_vars/win2016-compute-{{ zuul_project | basename }}-{{ job_type }}"
      failed_when: False
      tags: always

    - name: Include variables from group_vars/win2016-compute-{{ zuul_project | basename }}-{{ job_type }}-{{ network_type }}
      include_vars: "group_vars/win2016-compute-{{ zuul_project | basename }}-{{ job_type }}"
      failed_when: False
      when: network_type is defined
      tags: always
      
    - name: Include variables from job_vars/{{ zuul_project | basename }}
      include_vars: "job_vars/{{ zuul_project | basename }}"
      failed_when: False
      tags: always

    - name: Include variables from job_vars/{{ zuul_project | basename }}-{{ job_type }}
      include_vars: "job_vars/{{ zuul_project | basename }}-{{ job_type }}"
      failed_when: False
      tags: always
      
    - name: Include variables from job_vars/{{ zuul_project | basename }}-{{ job_type }}
      include_vars: "job_vars/{{ zuul_project | basename }}-{{ job_type }}-{{ network_type }}"
      failed_when: False
      when: network_type is defined
      tags: always

    - name: Get log files
      shell: |
        if [ ! -d "{{ item.value.dest }}" ];then
            mkdir -p "{{ item.value.dest }}"
        fi
        smbclient "//{{ inventory_hostname }}/C\$" -c "prompt OFF; cd {{ item.value.src }}" -U "administrator%Passw0rd"
        if [ $? -ne 0 ];then
            echo "Folder {{ item.value.src }} does not exists"
        else
            smbclient "//{{ inventory_hostname }}/C\$" -c "prompt OFF; recurse ON; lcd {{ item.value.dest }}; cd {{ item.value.src }}; mget *" -U "administrator%Passw0rd"
        fi
      args:
        executable: /bin/bash
      with_dict:
        log:
          dest: "{{ log_path }}/windows/logs/{{ hostname }}"
          src: '\openstack\log'
      ignore_errors: True
      delegate_to: 127.0.0.1

    - name: Get config files
      shell: |
        if [ ! -d "{{ item.value.dest }}" ];then
            mkdir -p "{{ item.value.dest }}"
        fi
        smbclient "//{{ inventory_hostname }}/C\$" -c "prompt OFF; cd {{ item.value.src }}" -U "administrator%Passw0rd"
        if [ $? -ne 0 ];then
            echo "Folder {{ item.value.src }} does not exists"
        else
            smbclient "//{{ inventory_hostname }}/C\$" -c "prompt OFF; recurse ON; lcd {{ item.value.dest }}; cd {{ item.value.src }}; mget *" -U "administrator%Passw0rd"
        fi
      args:
        executable: /bin/bash
      with_dict:
        log:
          dest: "{{ log_path }}/windows/confs/{{ hostname }}"
          src: '\openstack\etc'
      ignore_errors: True
      delegate_to: 127.0.0.1


