- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars_files:
    - zuul-params.yaml
  vars:
    vlan_range_tool: /home/jenkins-slave/vlan_ranges/vlan_range_tool.py  

  tasks:
    - name: Remove VLAN range for this build
      shell: "./{{ vlan_range_tool | basename}} -f {{ vlan_range }}"
      args:
        chdir: "{{ vlan_range_tool | dirname}}"
      register: vlan_range
      until: vlan_range.rc == 0
      retries: 3
      delay: 5
      ignore_errors: yes
