  - name: Create OVS bridge "{{ data_bridge }}"
    openvswitch_bridge:
      bridge: "{{ data_bridge  }}"
      fail_mode: secure
    when: data_interface is defined
    become: True
    tags: configure-ovs

  - name: Add interface "{{ data_interface }}" to OVS bridge "{{ data_bridge }}"
    openvswitch_port:
      bridge: "{{ data_bridge }}"
      port: "{{ data_interface }}"
    when: data_interface is defined
    become: True
    tags: configure-ovs

