- name: Run discover hosts to add computes to cell
  shell: nova-manage cell_v2 discover_hosts --verbose
  register: discover_hosts

- name: Show discover-hosts output
  debug: var=discover_hosts.stdout_lines
