  - name: Find data interface
    cb_find_data_interface:
      subnet: "{{ data_network }}"
    register: ifs
    when: data_interface is not defined
    tags: write-configs, configure-ovs

  - name: Set data_interface variable to "{{ ifs.data.name }}"
    set_fact:
      data_interface: "{{ ifs.data.name }} "
    when: data_interface is not defined and ifs.data.name != data_bridge
    tags: write-configs, configure-ovs

