  # Install zuul in a virtualenv, it messes with pbr and other openstack libraries
  - name: Install zuul version {{ zuul_version }}
    pip:
      virtualenv: "{{ devstack_dir.zuul }}"
      name: "{{ zuul_version }}"
      virtualenv_python: python2.7
    become: True
    tags: install-zuul
