### these 2 routes on eth0 & eth1 don't need to be added on the first place
  - name: Remove unwanted routes to data_plane network
    shell: |
      ip route del 192.168.0.0/22 dev eth0
      ip route del 192.168.0.0/22 dev eth1
    become: True
    failed_when: False

  - name: Run stack
    shell: |
      ./unstack.sh > /dev/null 2>&1
      ./stack.sh > /dev/null 2>&1
    args:
      chdir: "{{ devstack_dir.devstack }}"
    register: stack_result
    until: stack_result.rc == 0
    retries: 3
    delay: 5
    ignore_errors: yes
    tags: stack

  - name: Get last 35 lines from stack.sh.log
    shell: tail -35 /opt/stack/logs/stack.sh.log
    register: stack_log
    tags: stack

  - name: Show last 35 lines from stack.sh.log
    debug: var=stack_log
    tags: stack

  - fail:
      msg: "Failed stack"
    when: stack_result.rc != 0
    tags: stack

