- name: Create services and/or stop them if they are running
  win_service:
    name: "{{ item.name }}"
    display_name: "{{ item.name }}"
    description: "{{ item.description}}"
    state: stopped
    start_mode: manual
    path: "{{ win_dir.bin }}\\OpenStackService.exe {{ item.name }} {{ item.binary }} --config-file {{ item.config }}"
  with_items: "{{ services }}"
  tags: create-services

- include: create-folders.yaml
- include: install-utils.yaml
- include: install-python.yaml
- include: install-pip.yaml
- include: configure-pip-index.yaml
- include: install-git.yaml
- include: install-vcredist.yaml
- include: install-freerdp.yaml
- include: install-zuul.yaml
- include: prepare-git-repos.yaml

- name: Update setuptools
  win_shell: "pip install -c {{ win_dir.build }}\\requirements\\upper-constraints.txt -U setuptools"

- include: tasks/windows/install-project.yaml
  with_items: "{{ git_prep_projects }}"
  tags:  install-project

- name: Create config files
  win_template:
    src: "windows/{{ item }}"
    dest: "{{ win_dir.etc }}\\{{ item }}"
  with_items:
    - nova.conf
    - neutron-hyperv-agent.conf
    - policy.json
  tags: create-configs

- name: Create vmswitches
  cb_vmswitch:
    name: "{{ item.name }}"
    management: "{{ item.management }}"
    subnet: "{{ item.subnet }}"
    state: present
  with_items: "{{ vmswitches }}"
  tags: create-vmswitch

- name: Start services
  win_service:
    name: "{{ item.name }}"
    display_name: "{{ item.name }}"
    description: "{{ item.description}}"
    state: started
    start_mode: manual
    path: "{{ win_dir.bin }}\\OpenStackService.exe {{ item.name }} {{ item.binary }} --config-file {{ item.config }}"
  with_items: "{{ services }}"
  tags: start-services
