---
    - name: Install OVS
      win_package:
        path: "{{ ovs_msi_url }}"
        productid: '{A5CE0CD6-AABF-42AB-B52D-077492FF41A6}'
        ensure: present
      tags: configure-ovs
      
    - name: Check if OVS extension is installed
      win_shell: 'Get-VMSwitchExtension -VMSwitchName {{ item.name }} -Name "Cloudbase Open vSwitch Extension"'
      register: result
      tags: configure-ovs
      
    - name: Enable OVS extension on {{ item.name }}
      win_shell: 'Enable-VMSwitchExtension -VMSwitchName {{ item.name }} -Name "Cloudbase Open vSwitch Extension"'
      when: result.rc == 0
      tags: configure-ovs

    # - name: Add configure-ovs-bridge ps script
      # win_template:
        # src: windows/configure-ovs-bridge.ps1
        # dest: "{{ win_dir.tmp }}\\configure-ovs-bridge.ps1"

    # - name: Run configure-ovs-bridge ps script
      # win_shell: "{{ win_dir.tmp }}\\configure-ovs-bridge.ps1"

    # - name: Create {{ data_bridge }}
      # openvswitch_bridge:
        # bridge: "{{ data_bridge }}"
        # state: present
      # tags: configure-ovs

    # - name: Retrieve data network interface
      # win_shell: '(Get-NetIPAddress -AddressFamily ipv4 | Where-Object {$_.IPAddress -match "192.168.0"}|Select-Object InterfaceAlias).InterfaceAlias'
      # register: interface
      # tags: configure-ovs

    # - name: interface debug
      # debug:
        # msg: "interface name: {{ interface.stdout }}"

    # - name: Get IP address of data interface
      # win_shell: "(Get-NetIPAddress -AddressFamily ipv4 |Where-Object {$_.InterfaceAlias -match \"{{ interface.stdout }}\"}|Select-Object IPAddress).IPAddress"
      # register: interface_ip

    # - name: interface_ip debug
      # debug:
        # msg: "interface_ip: {{ interface_ip.stdout }}"

    # - name: Add the port in {{ data_bridge }}
      # openvswitch_port:
        # bridge: "{{ data_bridge }}"
        # port: "{{ interface.stdout }}"
        # state: present
      # tags: configure-ovs
    
    # - name: Enable {{ data_bridge }}
      # win_shell: "Enable-NetAdapter {{ data_bridge }}"
    
    # - name: Add IP address of bridge
      # win_shell: "New-NetIPAddress -IPAddress {{ interface_ip.stdout }} -InterfaceAlias {{ data_bridge }} -PrefixLength 22"
