---
- include: create-folders.yaml
- include: install-utils.yaml
- include: install-python.yaml
- include: install-pip.yaml
- include: configure-pip-index.yaml
- include: install-git.yaml
- include: install-vcredist.yaml
- include: install-freerdp.yaml
- include: install-zuul.yaml
